/** @type {import('tailwindcss').Config} */
/**
 * Hospitality Command tokens — source: context/ui-tokens.md
 * Prefer ui-tokens.md over design HTML if they disagree.
 */
module.exports = {
  content: [
    './app/views/**/*.php',
    './public/assets/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8faf7',
        'surface-dim': '#d8dbd8',
        'surface-bright': '#f8faf7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f1',
        'surface-container': '#eceeec',
        'surface-container-high': '#e7e9e6',
        'surface-container-highest': '#e1e3e0',
        'on-surface': '#191c1b',
        'on-surface-variant': '#3f4945',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1ef',
        outline: '#707975',
        'outline-variant': '#bfc9c4',
        'surface-tint': '#29695b',
        primary: '#00342b',
        'on-primary': '#ffffff',
        'primary-container': '#004d40',
        'on-primary-container': '#7ebdac',
        'inverse-primary': '#94d3c1',
        secondary: '#7e5700',
        'on-secondary': '#ffffff',
        'secondary-container': '#feb300',
        'on-secondary-container': '#6a4800',
        tertiary: '#4e2013',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#693527',
        'on-tertiary-container': '#e89f8c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#afefdd',
        'primary-fixed-dim': '#94d3c1',
        'on-primary-fixed': '#00201a',
        'on-primary-fixed-variant': '#065043',
        'secondary-fixed': '#ffdeac',
        'secondary-fixed-dim': '#ffba38',
        'on-secondary-fixed': '#281900',
        'on-secondary-fixed-variant': '#604100',
        'tertiary-fixed': '#ffdbd1',
        'tertiary-fixed-dim': '#ffb5a1',
        'on-tertiary-fixed': '#370e04',
        'on-tertiary-fixed-variant': '#6d382a',
        background: '#f8faf7',
        'on-background': '#191c1b',
        'surface-variant': '#e1e3e0',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sidebar: '240px',
        topbar: '56px',
        'container-margin': '24px',
        'cell-y': '8px',
        'cell-x': '12px',
        'stack-gap': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-mono': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        level2: '0 2px 4px rgba(0,0,0,0.05)',
      },
    },
  },
  plugins: [],
};
